apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  postgresql.conf: |
    # Enable logging to stderr
    log_destination = 'stderr'
    logging_collector = off

    # Log all statements, durations, connections, and disconnections
    log_statement = 'all'
    log_duration = on
    log_connections = on
    log_disconnections = on

    # Set log verbosity
    log_min_messages = info
    log_line_prefix = '%m [%p]: [%l-1] '
