apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:                 # Add the selector to match labels
    matchLabels:
      app: postgres          # This must match the labels in the template
  template:
    metadata:
      labels:
        app: postgres        # This must match the selector
    spec:
      containers:
      - name: postgres
        image: postgres:13.2
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DB
          value: "abc_db"
        args:
        - "-c"
        - "config_file=/etc/postgresql/postgresql.conf"
        volumeMounts:
        - name: postgres-config-volume
          mountPath: /etc/postgresql/postgresql.conf
          subPath: postgresql.conf
        ports:
        - containerPort: 5432
      volumes:
      - name: postgres-config-volume
        configMap:
          name: postgres-config
